version: "3.9"
services:
  pytmbot:
    container_name: "pytmbot"
    build:
      target: prod
      dockerfile: Dockerfile
    restart: always
    pid: 'host'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"