version: "3.9"
services:
  pytmbot:
    image: "orenlab/pytmbot:latest"
    container_name: "pytmbot"
    build:
      dockerfile: Dockerfile
    restart: always
    pid: 'host'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"