services:
  pytmbot:
    container_name: "pytmbot"
    build:
      context: .
      dockerfile: Dockerfile
      target: self_build
    restart: always
    pid: 'host'
    image: orenlab/pytmbot:self-build
    security_opt:
      - no-new-privileges
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/pytmbot/pytmbot.yaml:/opt/app/pytmbot.yaml:ro
    command:
      - --log_level INFO
      - --plugins monitor