[tool.poetry]
name = "pyTMBot"
version = "0.1.2-dev"
description = "A simple Telegram bot designed to gather basic information about the status of your local computers and/or servers from Glances"
authors = ["Denis Rozhnovskiy <pytelemonbot@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
emoji = "^2.9.0"
jinja2 = "^3.1.3"
pydantic = "^2.5.3"
pydantic-settings = "^2.1.0"
docker = "^7.0.0"
click = "^8.1.7"
humanize = "^4.9.0"
psutil = "^6.0.0"
pytelegrambotapi = "^4.21.0"
pyotp = "^2.9.0"
qrcode = "^7.4.2"
loguru = "^0.7.2"
pyjwt = "^2.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
