[tool.poetry]
name = "pyTMBot"
version = "2.0.0-dev"
description = "A simple Telegram bot to handle Docker containers and images, also providing basic information about the status of local servers."
authors = ["Denis Rozhnovskiy <pytelemonbot@mail.ru>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/orenlab/pytmbot"

[tool.poetry.dependencies]
python = "^3.12"
emoji = "^2.9.0"
jinja2 = "^3.1.3"
pydantic = "^2.5.3"
pydantic-settings = "^2.1.0"
docker = "^7.0.0"
humanize = "^4.9.0"
psutil = "^6.0.0"
pytelegrambotapi = "^4.21.0"
pyotp = "^2.9.0"
qrcode = "^7.4.2"
loguru = "^0.7.2"
pyyaml = "^6.0.2"

[tool.poetry.extras]
pyoutlineapi = ["pyoutlineapi"]
click = ["click"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"