#!/usr/local/bin/python3
"""
(c) Copyright 2025, Denis Rozhnovskiy <pytelemonbot@mail.ru>
pyTMBot - A simple Telegram bot to handle Docker containers and images,
also providing basic information about the status of local servers.
"""

from __future__ import annotations

import base64
import hashlib
import io
import re
import secrets
import threading
import time
from datetime import UTC, datetime
from typing import ClassVar, Final

import pyotp
import qrcode
from qrcode.image.pure import PyPNGImage

from pytmbot.exceptions import ErrorContext, QRCodeError, TOTPError
from pytmbot.globals import settings
from pytmbot.logs import BaseComponent


class TwoFactorAuthenticator(BaseComponent):
    """Two-factor authentication handler using TOTP (Time-based One-Time Password)."""

    # Constants
    TOTP_CODE_LENGTH: Final[int] = 6
    TOTP_DIGITS: Final[int] = 6
    TOTP_INTERVAL: Final[int] = 30
    HASH_DIGEST_SIZE: Final[int] = 64
    ISSUER_NAME: Final[str] = "pyTMbot TOTP"
    QR_CODE_FORMAT: Final[str] = "PNG"

    # Regex pattern for validating TOTP codes (6 digits)
    TOTP_CODE_PATTERN: Final[re.Pattern[str]] = re.compile(r"^\d{6}$")
    _REPLAY_WINDOW_STEPS: ClassVar[int] = 4
    _MAX_TRACKED_CODES_PER_USER: ClassVar[int] = 64
    _used_totp_codes: ClassVar[dict[int, set[tuple[str, int]]]] = {}
    _used_totp_codes_lock: ClassVar[threading.RLock] = threading.RLock()

    __slots__ = (
        "user_id",
        "username",
        "_salt",
        "_secret_cache",
        "_secret_key_material",
    )

    def __init__(self, user_id: int, username: str) -> None:
        """Initialize the TwoFactorAuthenticator with user ID and username.

        Args:
            user_id: The unique identifier for the user
            username: The username of the user

        Raises:
            TOTPError: If user_id or username is invalid
        """
        super().__init__("TwoFactorAuth")

        if not isinstance(user_id, int) or user_id <= 0:
            raise TOTPError(f"Invalid user_id: {user_id}. Must be a positive integer.")

        if not isinstance(username, str) or not username.strip():
            raise TOTPError(
                f"Invalid username: {username}. Must be a non-empty string."
            )

        self.user_id: int = user_id
        self.username: str = username.strip()
        self._salt: str = settings.access_control.auth_salt[0].get_secret_value()
        prod_token_values = settings.bot_token.prod_token or []
        dev_token_values = settings.bot_token.dev_bot_token or []
        prod_token = (
            prod_token_values[0].get_secret_value() if prod_token_values else ""
        )
        dev_token = dev_token_values[0].get_secret_value() if dev_token_values else ""
        self._secret_key_material = "|".join(
            segment for segment in (self._salt, prod_token, dev_token) if segment
        )
        if not self._secret_key_material:
            raise TOTPError("Missing TOTP key material")
        self._secret_cache: str | None = None  # Cache for secret to avoid regeneration

    def _generate_secret(self) -> str:
        """Generate a secret key for TOTP authentication.

        The secret key is generated by hashing the concatenation of the user ID,
        salt, and username using blake2b for enhanced security.

        Returns:
            str: The base32 encoded secret key

        Raises:
            TOTPError: If secret generation fails
        """
        if self._secret_cache is not None:
            return self._secret_cache

        try:
            # Generate a deterministic user secret from private key material.
            message = f"{self.user_id}:{self.username.lower()}".encode()
            key_material = hashlib.blake2b(
                self._secret_key_material.encode(),
                digest_size=32,
            ).digest()
            hash_obj = hashlib.blake2b(
                message,
                key=key_material,
                digest_size=self.HASH_DIGEST_SIZE,
            )

            # Encode the hash digest as base32 and decode it to a string
            self._secret_cache = base64.b32encode(hash_obj.digest()).decode("ascii")

            with self.log_context(user_id=self.user_id, username=self.username) as log:
                log.debug("bot.utils.totp.secret.generated.debug")

            return self._secret_cache

        except Exception as e:
            with self.log_context(user_id=self.user_id, username=self.username) as log:
                log.error("bot.utils.totp.secret.generation.fail")
            raise TOTPError(
                f"Failed to generate secret for user {self.username}: {e}"
            ) from e

    def _generate_totp_auth_uri(self) -> str:
        """Generate a TOTP authentication URI using the secret key and account information.

        Returns:
            str: The generated TOTP authentication URI

        Raises:
            TOTPError: If URI generation fails
        """
        try:
            # Generate TOTP object using the secret key
            totp = pyotp.TOTP(
                self._generate_secret(),
                digits=self.TOTP_DIGITS,
                interval=self.TOTP_INTERVAL,
            )

            # Generate the URI using the TOTP object and account name
            uri = totp.provisioning_uri(
                name=self.username, issuer_name=self.ISSUER_NAME
            )

            with self.log_context(user_id=self.user_id, username=self.username) as log:
                log.debug("bot.utils.totp.uri.generated.debug")

            return uri

        except Exception as e:
            with self.log_context(user_id=self.user_id, username=self.username) as log:
                log.error("bot.utils.totp.uri.generation.fail")
            raise TOTPError(
                f"Failed to generate TOTP URI for user {self.username}: {e}"
            ) from e

    def generate_totp_qr_code(self) -> bytes:
        """Generate a QR code for two-factor authentication.

        Returns:
            bytes: The generated QR code as bytes

        Raises:
            QRCodeError: If QR code generation fails
        """
        with self.log_context(
            user_id=self.user_id, username=self.username, operation="qr_generation"
        ) as log:
            log.debug("bot.utils.totp.qr.code.start")

            try:
                # Generate the TOTP authentication URI
                auth_uri = self._generate_totp_auth_uri()

                # Use pure-Python PNG backend (PyPNGImage) to avoid Pillow dependency.
                qr_code = qrcode.make(auth_uri, image_factory=PyPNGImage)

                # Save the QR code as bytes in a BytesIO object
                with io.BytesIO() as img_bytes:
                    qr_code.save(img_bytes)
                    qr_data = img_bytes.getvalue()

                log.info("bot.utils.totp.qr.code.info", qr_size=len(qr_data))
                return qr_data

            except TOTPError:
                log.error("bot.utils.totp.qr.code.fail")
                raise QRCodeError(
                    ErrorContext(
                        message="QR code generation failed due to TOTP error.",
                        error_code="QR_CODE_TOTP_ERROR",
                        metadata={"username": self.username, "user_id": self.user_id},
                    )
                )
            except Exception as e:
                log.error("bot.utils.totp.qr.code.fail")
                raise QRCodeError(
                    ErrorContext(
                        message="QR code generation failed.",
                        error_code="QR_CODE_GENERATION_ERROR",
                        metadata={
                            "username": self.username,
                            "user_id": self.user_id,
                            "original_error": str(e),
                        },
                    )
                ) from e

    def verify_totp_code(self, code: str) -> bool:
        """Verify the TOTP code for the user.

        Args:
            code: The TOTP code to be verified

        Returns:
            bool: True if the TOTP code is verified, False otherwise

        Raises:
            TOTPError: If verification process fails critically
        """
        with self.log_context(
            user_id=self.user_id, username=self.username, operation="totp_verification"
        ) as log:
            # Input validation
            if not isinstance(code, str):
                log.debug("bot.utils.totp.invalid.code.debug")
                return False

            # Clean and validate code format
            cleaned_code = code.strip()
            if not self.TOTP_CODE_PATTERN.match(cleaned_code):
                log.debug("bot.utils.totp.invalid.code.debug")
                return False

            try:
                totp = pyotp.TOTP(
                    self._generate_secret(),
                    digits=self.TOTP_DIGITS,
                    interval=self.TOTP_INTERVAL,
                )

                log.debug("bot.utils.totp.verification.start")

                current_step = int(time.time()) // self.TOTP_INTERVAL
                matched_step = self._resolve_matching_step(
                    totp=totp,
                    code=cleaned_code,
                    current_step=current_step,
                )

                if matched_step is None:
                    log.warning(
                        "bot.utils.totp.verification.fail",
                        code_length=len(cleaned_code),
                    )
                    return False

                if not self._register_code_usage(
                    cleaned_code, matched_step, current_step
                ):
                    log.warning("bot.utils.totp.verification.replay.fail")
                    return False

                log.info("bot.utils.totp.verification.ok")
                return True

            except Exception as e:
                log.error("bot.utils.totp.critical.verification.fail")
                raise TOTPError(
                    f"TOTP verification failed for user {self.username}: {e}"
                ) from e

    def _resolve_matching_step(
        self, totp: pyotp.TOTP, code: str, current_step: int
    ) -> int | None:
        """Resolve the exact time-step for a code inside verification window."""
        for step in range(current_step - 1, current_step + 2):
            step_time = datetime.fromtimestamp(step * self.TOTP_INTERVAL, tz=UTC)
            if totp.verify(code, for_time=step_time, valid_window=0):
                return step
        return None

    def _register_code_usage(
        self, code: str, matched_step: int, current_step: int
    ) -> bool:
        """Reject replayed TOTP codes and track successful code usage."""
        min_step = current_step - self._REPLAY_WINDOW_STEPS
        code_marker = (code, matched_step)

        with self._used_totp_codes_lock:
            user_entries = {
                marker
                for marker in self._used_totp_codes.get(self.user_id, set())
                if marker[1] >= min_step
            }
            if code_marker in user_entries:
                self._used_totp_codes[self.user_id] = user_entries
                return False

            user_entries.add(code_marker)
            if len(user_entries) > self._MAX_TRACKED_CODES_PER_USER:
                sorted_entries = sorted(user_entries, key=lambda marker: marker[1])
                user_entries = set(sorted_entries[-self._MAX_TRACKED_CODES_PER_USER :])
            self._used_totp_codes[self.user_id] = user_entries
            return True

    def get_backup_codes(self, count: int = 10) -> list[str]:
        """Generate backup codes for the user.

        Args:
            count: Number of backup codes to generate

        Returns:
            list[str]: List of backup codes

        Raises:
            TOTPError: If backup code generation fails
        """
        if not isinstance(count, int) or count <= 0 or count > 20:
            raise TOTPError(
                f"Invalid backup code count: {count}. Must be between 1 and 20."
            )

        with self.log_context(
            user_id=self.user_id,
            username=self.username,
            operation="backup_codes_generation",
            count=count,
        ) as log:
            try:
                # Ensure secret is initialized and validated before generating backup codes.
                _ = self._generate_secret()
                backup_codes = []

                for _ in range(count):
                    code = base64.b32encode(secrets.token_bytes(5)).decode("ascii")[:8]
                    backup_codes.append(f"{code[:4]}-{code[4:]}")

                log.info("bot.utils.totp.generated.backup.info")
                return backup_codes

            except Exception as e:
                log.error("bot.utils.totp.backup.codes.fail")
                raise TOTPError(
                    f"Failed to generate backup codes for user {self.username}: {e}"
                ) from e
