services:
  influxdb:
    image: influxdb:2-alpine
    security_opt:
      - no-new-privileges
    container_name: influxdb
    ports:
      - "127.0.0.1:8086:8086"
    restart: on-failure
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      # Optional variables for initial configuration
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket

volumes:
  influxdb_data: