services:
  influxdb:
    # Using lightweight Alpine image to optimize size
    # See https://hub.docker.com/r/influxdb/influxdb/tags
    image: influxdb:3-core
    # Prevent the container from gaining additional privileges for security
    security_opt:
      - no-new-privileges
    # Drop all capabilities to ensure the container runs with minimal privileges
    cap_drop:
      - ALL
    container_name: influxdb
    # Expose InfluxDB port only on localhost for increased security.
    # Use Nginx proxy if you want to expose the port to the internet
    ports:
      - "8086:8086"

    # Restart the container only on failure for reliability
    restart: on-failure
