name: Push Alpine Dev Image for 0.2.0

on:
  push:
    branches:
      - 'feature/0.2.0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          target: production
          sbom: True
          provenance: True
          file: Dockerfile
          push: true
          tags: orenlab/pytmbot:0.2.0-alpine-dev