name: CI Rebuild All Supported Tags

on:
  schedule:
    - cron: '30 17 * * 5'
  workflow_dispatch: # Allow manual trigger

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Get all supported tags
        id: get_tags
        run: |
          # Retrieve all tags in 0.0.0 format starting from 0.2.0
          min_version="0.2.0"
          tags=$(git tag -l | sort -V | awk -v min_version="$min_version" '$0 >= min_version' | sed 's/^/orenlab\/pytmbot:/')
          latest_tag=$(echo "$tags" | tail -n 1)
          
          # Convert tags to JSON array format for build-push-action
          tags_json=$(echo "$tags" | tr '\n' ',' | sed 's/,$//')
          echo "tags_json=$tags_json" >> $GITHUB_OUTPUT
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          target: production
          platforms: linux/amd64,linux/arm64
          sbom: true
          provenance: true
          file: Dockerfile
          push: true
          tags: |
            ${{ steps.get_tags.outputs.tags_json }}
            orenlab/pytmbot:latest