name: CI Rebuild All Supported Tags

on:
  schedule:
    - cron: '0 13 * * 4' # Run every Thursday at 13:00 UTC (18:00 Yekaterinburg time)
  workflow_dispatch: # Allow manual trigger

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Set up git and clone the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Retrieve all tags and filter by minimum version
      - name: Get all supported tags
        id: get_tags
        run: |
          git fetch --tags
          # Retrieve all tags in 0.0.0 format starting from 0.2.0
          min_version="0.2.0"
          tags=$(git tag -l | sort -V | awk -v min_version="$min_version" '$0 >= min_version')
          latest_tag=$(echo "$tags" | tail -n 1)
          echo "tags=$tags" >> $GITHUB_ENV
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker images
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: --target prod
          sbom: true
          provenance: true
          file: hub.Dockerfile
          push: true
          tags: |
            ${{ join(fromJson(env.tags), ',') }}
            orenlab/pytmbot:latest