name: Push Alpine Dev Image

on:
  push:
    branches:
      - '**'  # слушаем все ветки

permissions:
  contents: read
  packages: write
  id-token: write
  security-events: write

jobs:
  push_dev_image:
    if: |
      startsWith(github.ref, 'refs/heads/fix/') ||
      startsWith(github.ref, 'refs/heads/feat/') ||
      startsWith(github.ref, 'refs/heads/master/') ||
    name: Build and Push Dev Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: |
            image=moby/buildkit:v0.12.5

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: orenlab/pytmbot
          tags: |
            type=raw,value=alpine-dev
          labels: |
            org.opencontainers.image.title=pyTMbot
            org.opencontainers.image.description=Versatile Telegram bot designed for managing Docker containers, monitoring server status, and extending its functionality through a modular plugin system
            org.opencontainers.image.source=https://github.com/orenlab/pytmbot

      - uses: docker/build-push-action@v5
        id: build-and-push
        with:
          context: .
          target: production
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: mode=max
          sbom: true