name: Push Alpine Dev Image

on:
  push:
    branches:
      - '0.2.2'

permissions:
  contents: read
  packages: write
  id-token: write
  security-events: write

jobs:
  push_dev_image:
    name: Build and Push Dev Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: |
            image=moby/buildkit:v0.12.5

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: orenlab/pytmbot
          tags: |
            type=raw,value=alpine-dev
          labels: |
            org.opencontainers.image.title=pyTMbot
            org.opencontainers.image.description=Versatile Telegram bot designed for managing Docker containers, monitoring server status, and extending its functionality through a modular plugin system
            org.opencontainers.image.source=https://github.com/orenlab/pytmbot

      - uses: docker/build-push-action@v5
        id: build-and-push
        with:
          context: .
          target: production
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max

      - name: Get Image Digest
        id: get-digest
        run: |
          IMAGE_REF="orenlab/pytmbot:alpine-dev"
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "${IMAGE_REF}")
          echo "IMAGE_DIGEST=${DIGEST}" >> $GITHUB_ENV

      - name: Sign the Image Digest
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          IMAGE_DIGEST=${{ env.IMAGE_DIGEST }}
          cosign sign --yes "${IMAGE_DIGEST}"

      - name: Create SBOM Attestation
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          IMAGE_DIGEST=${{ env.IMAGE_DIGEST }}
          cosign attest --predicate sbom.json --type https://spdx.dev/Document "${IMAGE_DIGEST}"

      - name: Run Vulnerability Scan
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: orenlab/pytmbot:alpine-dev
          fail-build: false
          severity-cutoff: high
          acs-report-enable: true
          sarif-file: results.sarif

      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: results.sarif