name: Tests for slimtoolkit/slim

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Build the Docker image first
      - uses: docker/build-push-action@v5
        with:
          push: false
          tags: pytmbot:alpine-slim-dev

      # Slim the Image
      - uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: pytmbot
          tag: "alpine-slim-dev"

      # Docker Hub Login
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push to the registry
      - run: |
          docker tag pytmbot:alpine-slim-dev ${{ secrets.DOCKER_USERNAME }}/pytmbot:alpine-slim-dev
          docker push ${{ secrets.DOCKER_USERNAME }}/pytmbot:alpine-slim-dev