name: Tests for slimtoolkit/slim

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Build the Docker image first
      - uses: docker/build-push-action@v5
        with:
          push: false
          tags: IMAGE_NAME:{{github.run_number}}

      # Slim the Image
      - uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: IMAGE_NAME:{{github.run_number}}
          tag: "slim-{{github.run_number}}"

      # Docker Hub Login
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push to the registry
      - run: |
          docker tag IMAGE_NAME:slim-{{github.run_number}} ${{ secrets.DOCKER_USERNAME }}/IMAGE_NAME:slim-{{github.run_number}}
          docker push ${{ secrets.DOCKER_USERNAME }}/IMAGE_NAME:slim-{{github.run_number}}